version: 0.2
env:
  variables:
    APP_NAME: "angular-cognito-demo"
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo install process started
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo build process started now
      - ng build --configuration=production
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd dist/authdemo
      - ls -la
      - aws s3 sync . s3://angular-cognito-demo-2503 --delete